name: Run Experiment
run-name: Run Experiment
on:
  push:
    branches:
      - main
jobs:
  Run-Experiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          source set-up-env
          source run-experiment
          git checkout -b ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
          git add .
          git commit -m "experiment result"
          git push --set-upstream origin ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
